-- Foundation for honest attribution: where a booking came from, and a durable
-- log of every status transition (so "prevented no-show" claims can point to
-- an actual confirmed->completed row instead of an inference).

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'app'
  CHECK (source IN ('app', 'walk_in', 'phone', 'admin'));

CREATE TABLE IF NOT EXISTS booking_status_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id uuid NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
  tenant_id uuid NOT NULL REFERENCES tenants(id),
  old_status text,
  new_status text NOT NULL,
  changed_at timestamptz NOT NULL DEFAULT now(),
  changed_by uuid REFERENCES auth.users(id)
);

CREATE INDEX IF NOT EXISTS booking_status_history_booking_id_idx
  ON booking_status_history(booking_id);

ALTER TABLE booking_status_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation ON booking_status_history;
CREATE POLICY tenant_isolation ON booking_status_history
FOR ALL
USING (tenant_id = get_my_tenant_id());

-- Auto-log every insert/status change so the history can't drift from reality
-- by relying on app code remembering to write it.
CREATE OR REPLACE FUNCTION log_booking_status_change()
RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'INSERT' OR OLD.status IS DISTINCT FROM NEW.status THEN
    INSERT INTO booking_status_history (booking_id, tenant_id, old_status, new_status, changed_by)
    VALUES (
      NEW.id,
      NEW.tenant_id,
      CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.status END,
      NEW.status,
      auth.uid()
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

DROP TRIGGER IF EXISTS bookings_status_history_trigger ON bookings;
CREATE TRIGGER bookings_status_history_trigger
AFTER INSERT OR UPDATE ON bookings
FOR EACH ROW EXECUTE FUNCTION log_booking_status_change();
